In [ ]:
#"Lab 5 (Data Loading): Creating NumPy arrays, reading CSV files, introducing pandas
#Series/DataFrames, and performing basic indexing, filtering, and summary operations,
#along with inspecting shape, columns, and data types."

# Lab 5 (Data Loading)
In this lab you will learn about
* Creating NumPy Arrays
* Reading CSV Files
* Pandas Series
* Pandas DataFrames
* Basic Indexing and Filtering
* Summary Operations
* Inspecting Shape, Columns, and Data Types

### ▶ **Creating NumPy Arrays**
NumPy is the core library for numerical computing in Python. Its main object is the n-dimensional array, which is much faster and more memory-efficient than a normal Python list when doing numerical operations.

**Why not just use lists?**

Python lists can hold mixed data types and are flexible, but that flexibility makes them slow for math operations. NumPy arrays store data of a single type in contiguous memory, so operations on them are vectorized and fast.

First, we need to import the library. The common convention is to import it as `np`.

In [ ]:
import numpy as np
# Creating a 1D array from a list
a = np.array([10, 20, 30, 40, 50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


**Creating 2D arrays (matrices)**

You can pass a list of lists to `np.array()` to create a 2D array.

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


**Other handy ways to create arrays**

 `np.zeros(shape)` – array filled with 0's

 `np.ones(shape)` – array filled with 1's

 `np.arange(start, stop, step)` – like Python's `range()` but returns an array

 `np.linspace(start, stop, num)` – `num` evenly spaced values between start and stop

 `np.random.rand(shape)` – array of random values between 0 and 1

In [ ]:
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 3))
range_arr = np.arange(0, 10, 2)
lin_arr = np.linspace(0, 1, 5)
print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Arange:", range_arr)
print("Linspace:", lin_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


**Array attributes**Every NumPy array has some useful attributes that tell you about its structure:* `.shape` – dimensions of the array (rows, columns)* `.ndim` – number of dimensions* `.size` – total number of elements* `.dtype` – data type of the elements

In [ ]:
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Size:", b.size)
print("Dtype:", b.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Dtype: int64


**Reshaping arrays**`.reshape()` lets you change the shape of an array without changing its data, as long as the total number of elements stays the same.

In [ ]:
c = np.arange(1, 13)
print("Original:", c)
c_reshaped = c.reshape(3, 4)
print("Reshaped (3x4):\n", c_reshaped)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## ▶ Reading CSV Files

CSV (Comma Separated Values) is one of the most common formats for storing tabular data. Python's **pandas** library makes it very easy to load a CSV file into a table-like structure called a **DataFrame**.

For this lab we'll use a real-world **Amazon India product dataset** (`amazon.csv`) — 1465 products scraped from Amazon, with pricing, ratings, categories, and customer review data. Real datasets like this are rarely clean, which makes it a great way to learn what data loading actually looks like in practice. The dataset is provided to you already.

**Loading the file in VS Code**

Since you're running this notebook locally in VS Code (with the Jupyter extension), there's no upload button needed you just need the CSV file to be accessible on your computer, and you need to point `pd.read_csv()` to its correct path.

1. Download **`amazon.csv`** provided with this notebook.
2. Place it somewhere convenient e.g., the same folder as this notebook (recommended)
3. Note the **full path** to the file on your system.
4. Run the cell below with the path updated.

 **Note:** The path used in the code cell (e.g., `pd.read_csv("/content/amazon.csv")`) is a placeholder from a Google Colab environment. Since you're working in VS Code, replace it with your own file path, for example:


In [ ]:
import pandas as pd
df = pd.read_csv("C:/Users/YourName/Downloads/amazon.csv")
df

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the me

**A quick peek at the data*** `

.head(n)` – first `n` rows

.tail(n)` – last `n` rows

By default 5 rows are shown

In [ ]:
print(df.head())

   product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399   
1  Computers&Accessories|Accessories&Peripherals|...             ₹199   
2  Computers&Accessories|Accessories&Peripherals|...             ₹199   
3  Computers&Accessories|Accessories&Peripherals|...             ₹329   
4  Computers&Accessories|Accessories&Peripherals|...             ₹154   

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269   
1         ₹349                 43%  

In [ ]:

print(df.tail(3))

      product_id                                       product_name  \
1462  B009P2LIL4  Bajaj Majesty RX10 2000 Watts Heat Convector R...   
1463  B00J5DYCCA  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...   
1464  B01486F4G6  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...   

                                               category discounted_price  \
1462  Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...           ₹2,219   
1463  Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...           ₹1,399   
1464  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,863   

     actual_price discount_percentage rating rating_count  \
1462       ₹3,080                 28%    3.6          468   
1463       ₹1,890                 26%      4        8,031   
1464       ₹3,690                 22%    4.3        6,987   

                                          about_product  \
1462  International design and styling|Two heat sett...   
1463  Fan sweep area: 230 MM ; Noise level: (40

### ▶ **Inspecting Shape, Columns, and Data Types**

Before doing anything else with a new dataset, it's good practice to inspect its structure:*

`.shape` – (rows, columns)*

`.columns` – list of column names*

`.dtypes` – data type of each column*

`.info()` – a concise summary of the DataFrame (dtypes, non-null counts, memory usage)

In [ ]:
print("Shape:", df.shape)
print()
print("Columns:", df.columns)
print()
print("Dtypes:\n", df.dtypes)

Shape: (1465, 16)

Columns: Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='object')

Dtypes:
 product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: obj

**Notice something?** Columns like `discounted_price`, `actual_price`, `discount_percentage`, `rating`, and `rating_count` all show up as `object` (text) dtype instead of numbers! That's because they contain symbols like `₹`, `%`, and `,` — very common in real, uncleaned CSV data. We can't compute a mean or filter numerically on a text column, so let's clean these up next.

### ▶ **A Quick Data Cleaning Step**

We'll strip out the extra symbols and convert these columns to proper numeric types using `.str.replace()` and `pd.to_numeric()`. Setting `errors="coerce"` turns any value that still can't be converted (like a stray `|` in the ratings column) into `NaN` instead of crashing.

In [ ]:
#This line cleans up the discounted_price column, which stores values like "₹1,099" as plain text. The first .str.replace("₹", "", regex=False) strips out the rupee symbol, turning "₹399" into "399".
#That result is immediately chained into a second .str.replace(",", "", regex=False), which removes commas, turning "1,099" into "1099"
#Once the string is a clean number, .astype(float) converts it from text into an actual numeric type so it can be used in math, comparisons, and aggregation.
#The regex=False argument just tells pandas to treat "₹" and "," as literal characters rather than regex patterns.
df["discounted_price"] = df["discounted_price"].str.replace("₹", "", regex=False).str.replace(",", "", regex=False).astype(float)
df["actual_price"] = df["actual_price"].str.replace("₹", "", regex=False).str.replace(",", "", regex=False).astype(float)
df["discount_percentage"] = df["discount_percentage"].str.replace("%", "", regex=False).astype(float)
df["rating_count"] = df["rating_count"].str.replace(",", "", regex=False)
#This converts the now comma-free rating_count strings into numbers using pd.to_numeric() instead of .astype(float).
#The reason for the switch is that rating_count has a couple of missing or blank entries, which would cause .astype(float) to crash.
#pd.to_numeric() with errors="coerce" is more forgiving — anything it can't convert becomes NaN instead of raising an error, so the rest of the column still converts successfully.
df["rating_count"] = pd.to_numeric(df["rating_count"], errors="coerce")
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")


product_id              object
product_name            object
category                object
discounted_price       float64
actual_price           float64
discount_percentage    float64
rating                 float64
rating_count           float64
about_product           object
user_id                 object
user_name               object
review_id               object
review_title            object
review_content          object
img_link                object
product_link            object
dtype: object


Much better — these are now `float64` columns we can actually do math on. The `category` column is also a bit messy: it stores a full hierarchy like `Electronics|Mobiles|SmartWatches` separated by `|`. Let's pull out just the top-level category for easier grouping later.

In [ ]:
# This line creates a new column called "main_category" from the existing "category" column.
# The .str.split("|") splits each category wherever the "|" symbol appears.
# For example, "Electronics|Mobiles|Smartphones" becomes ["Electronics", "Mobiles", "Smartphones"].
# The .str[0] selects the first element, "Electronics", which represents the main category.
# This value is then stored in the new "main_category" column.

df["main_category"] = df["category"].str.split("|").str[0]

# This line counts how many times each unique main category appears in the "main_category" column.
# It helps us understand how many products belong to each main category.
# The results are then printed on the screen.

print(df["main_category"].value_counts())

main_category
Electronics              526
Computers&Accessories    453
Home&Kitchen             448
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64


### ▶ **Pandas Series**
A **Series** is a one-dimensional labeled array — think of it as a single column of a DataFrame, or a supercharged list where each value has an associated index label.

In [ ]:
marks = pd.Series([85, 90, 78, 92], index=["Math", "Physics", "Chemistry", "Biology"])
print(marks)

Math         85
Physics      90
Chemistry    78
Biology      92
dtype: int64


You can access elements by their **label** or by their **position**.

In [ ]:
print(marks["Physics"])   # by label
print(marks.iloc[1])       # by position

90
90


A single column of a DataFrame is itself a Series.

In [ ]:
ratings = df["rating"]
print(ratings)
print(type(ratings))

0       4.2
1       4.0
2       3.9
3       4.2
4       4.2
       ... 
1460    4.0
1461    4.1
1462    3.6
1463    4.0
1464    4.3
Name: rating, Length: 1465, dtype: float64
<class 'pandas.core.series.Series'>


### ▶ **Pandas DataFrames**

A **DataFrame** is a 2D labeled table, like a spreadsheet or SQL table. It's made up of multiple Series (columns) that share the same index.

You can build a DataFrame directly from a dictionary, where keys become column names.

In [ ]:
data = {
        "Product": ["Pen", "Notebook", "Eraser", "Sharpener"],
        "Price": [10, 40, 5, 8],
        "Stock": [100, 60, 200, 150]}
products_df = pd.DataFrame(data)
products_df

,Product,Price,Stock
0,Pen,10,100
1,Notebook,40,60
2,Eraser,5,200
3,Sharpener,8,150


### ▶ **Basic Indexing**

Pandas gives you a few different ways to select data from the Amazon DataFrame (`df`):
* `df["col"]` or `df[["col1", "col2"]]` – select column(s)
* `df.loc[]` – select rows/columns by **label**
* `df.iloc[]` – select rows/columns by **integer position**

In [ ]:
# Selecting a single column
print(df["product_name"])

0       Wayona Nylon Braided USB to Lightning Fast Cha...
1       Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2       Sounce Fast Phone Charging Cable & Data Sync U...
3       boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4       Portronics Konnect L 1.2M Fast Charging 3A 8 P...
                              ...                        
1460    Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1461    Prestige Delight PRWO Electric Rice Cooker (1 ...
1462    Bajaj Majesty RX10 2000 Watts Heat Convector R...
1463    Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1464    Borosil Jumbo 1000-Watt Grill Sandwich Maker (...
Name: product_name, Length: 1465, dtype: object


In [ ]:
# Selecting multiple columns
print(df[["product_name", "discounted_price", "rating"]])

                                           product_name  discounted_price  \
0     Wayona Nylon Braided USB to Lightning Fast Cha...             399.0   
1     Ambrane Unbreakable 60W / 3A Fast Charging 1.5...             199.0   
2     Sounce Fast Phone Charging Cable & Data Sync U...             199.0   
3     boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...             329.0   
4     Portronics Konnect L 1.2M Fast Charging 3A 8 P...             154.0   
...                                                 ...               ...   
1460  Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...             379.0   
1461  Prestige Delight PRWO Electric Rice Cooker (1 ...            2280.0   
1462  Bajaj Majesty RX10 2000 Watts Heat Convector R...            2219.0   
1463  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...            1399.0   
1464  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...            2863.0   

      rating  
0        4.2  
1        4.0  
2        3.9  
3        4.2  


In [ ]:
# loc - label based
print(df.loc[0])                                        # first row (by label/index)
print(df.loc[0, "product_name"])                        # value at row 0, column 'product_name'
print(df.loc[0:2, ["product_name", "rating"]])          # slice of rows, specific columns

product_id                                                    B07JW9H4J1
product_name           Wayona Nylon Braided USB to Lightning Fast Cha...
category               Computers&Accessories|Accessories&Peripherals|...
discounted_price                                                   399.0
actual_price                                                      1099.0
discount_percentage                                                 64.0
rating                                                               4.2
rating_count                                                     24269.0
about_product          High Compatibility : Compatible With iPhone 12...
user_id                AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
user_name              Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
review_id              R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
review_title           Satisfied,Charging is really fast,Value for mo...
review_content         Looks durable Charging is fi

In [ ]:
# iloc - position based
print(df.iloc[0])          # first row
print(df.iloc[0, 1])       # row 0, column at position 1 (product_name)
print(df.iloc[0:3, 0:3])   # first 3 rows, first 3 columns

product_id                                                    B07JW9H4J1
product_name           Wayona Nylon Braided USB to Lightning Fast Cha...
category               Computers&Accessories|Accessories&Peripherals|...
discounted_price                                                   399.0
actual_price                                                      1099.0
discount_percentage                                                 64.0
rating                                                               4.2
rating_count                                                     24269.0
about_product          High Compatibility : Compatible With iPhone 12...
user_id                AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
user_name              Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
review_id              R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
review_title           Satisfied,Charging is really fast,Value for mo...
review_content         Looks durable Charging is fi



```
# This is formatted as code
```

### ▶ **Filtering**

You can filter rows using **boolean conditions**, similar to how you'd filter a list with a condition, but pandas does it in a vectorized way across the whole column.

In [ ]:
# Products rated above 4.5
print(df[df["rating"] > 4.5])

      product_id                                       product_name  \
137   B08TGG316Z  10k 8k 4k HDMI Cable, Certified 48Gbps 1ms Ult...   
174   B0BP7XLX48  Syncwire LTG to USB Cable for Fast Charging Co...   
249   B09WN3SRC7  Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...   
324   B0BQRJ3C47  REDTECH USB-C to Lightning Cable 3.3FT, [Apple...   
447   B095RTJH1M  Spigen EZ Fit Tempered Glass Screen Protector ...   
459   B0B23LW7NV  Spigen EZ Fit Tempered Glass Screen Protector ...   
468   B0B244R4KB  Spigen EZ Fit Tempered Glass Screen Protector ...   
571   B0B9BXKBC7  WeCool S5 Long Selfie Stick, with Large Reinfo...   
775   B09ZHCJDP1  Amazon Basics Wireless Mouse | 2.4 GHz Connect...   
820   B01J1CFO5I  Redgear MP35 Speed-Type Gaming Mousepad (Black...   
853   B07X2L5Z8C  Logitech Pebble M350 Wireless Mouse with Bluet...   
886   B01MQ2A86A  Logitech M331 Silent Plus Wireless Mouse, 2.4G...   
964   B00NFD0ETQ  Logitech G402 Hyperion Fury USB Wired Gaming M...   
976   

In [ ]:
# Products in the Electronics main category
print(df[df["main_category"] == "Electronics"])

      product_id                                       product_name  \
12    B07KSMBL2H  AmazonBasics Flexible Premium HDMI Cable (Blac...   
16    B0B6F7LX4C  MI 80 cm (32 inches) 5A Series HD Ready Smart ...   
19    B08DPLCM6T  LG 80 cm (32 inches) HD Ready Smart LED TV 32L...   
21    B085194JFL  tizum HDMI to VGA Adapter Cable 1080P for Proj...   
22    B09F6S8BT6  Samsung 80 cm (32 Inches) Wondertainment Serie...   
...          ...                                                ...   
1012  B014SZPBM4           Duracell Ultra Alkaline D Battery, 2 Pcs   
1015  B078W65FJ7  boAt BassHeads 900 On-Ear Wired Headphones wit...   
1016  B08S74GTBT  Zebronics Astra 10 Portable Wireless BT v5.0 S...   
1017  B0B9BD2YL4  KINGONE Wireless Charging Pencil (2nd Generati...   
1021  B07W7Z6DVL  Infinity (JBL Fuze 100, Wireless Portable Blue...   

                                               category  discounted_price  \
12    Electronics|HomeTheater,TV&Video|Accessories|C...             21

You can also combine multiple conditions using `&` (and), `|` (or). Each condition must be wrapped in parentheses.

In [ ]:
# Electronics products with a discount of over 50%
print(df[(df["main_category"] == "Electronics") & (df["discount_percentage"] > 50)])

      product_id                                       product_name  \
12    B07KSMBL2H  AmazonBasics Flexible Premium HDMI Cable (Blac...   
25    B01M4GGIVU  Tizum High Speed HDMI Cable with Ethernet | Su...   
48    B09L8DSSFH  7SEVEN® Compatible for Samsung Smart 4K Ultra ...   
55    B01N90RZ4M                          Tata Sky Universal Remote   
60    B07B275VN9  Airtel DigitalTV DTH Television, Setup Box Rem...   
...          ...                                                ...   
999   B08SMJT55F  boAt Stone 250 Portable Wireless Speaker with ...   
1007  B0B9BXKBC7  WeCool S5 Long Selfie Stick, with Large Reinfo...   
1015  B078W65FJ7  boAt BassHeads 900 On-Ear Wired Headphones wit...   
1016  B08S74GTBT  Zebronics Astra 10 Portable Wireless BT v5.0 S...   
1017  B0B9BD2YL4  KINGONE Wireless Charging Pencil (2nd Generati...   

                                               category  discounted_price  \
12    Electronics|HomeTheater,TV&Video|Accessories|C...             21

### ▶ **Summary Operations**

Pandas provides quick built-in methods to summarize your data:
* `.describe()` – summary statistics for numeric columns
* `.mean()`, `.sum()`, `.min()`, `.max()`, `.median()`, `.std()` – column-wise stats
* `.value_counts()` – frequency count of unique values (useful on a single column)

In [ ]:
print(df.describe())

       discounted_price   actual_price  discount_percentage       rating  \
count       1465.000000    1465.000000          1465.000000  1464.000000   
mean        3125.310874    5444.990635            47.691468     4.096585   
std         6944.304394   10874.826864            21.635905     0.291674   
min           39.000000      39.000000             0.000000     2.000000   
25%          325.000000     800.000000            32.000000     4.000000   
50%          799.000000    1650.000000            50.000000     4.100000   
75%         1999.000000    4295.000000            63.000000     4.300000   
max        77990.000000  139900.000000            94.000000     5.000000   

        rating_count  
count    1463.000000  
mean    18295.541353  
std     42753.864952  
min         2.000000  
25%      1186.000000  
50%      5179.000000  
75%     17336.500000  
max    426973.000000  


In [ ]:
print("Average Rating:", df["rating"].mean())
print("Highest Discounted Price:", df["discounted_price"].max())
print("Lowest Discounted Price:", df["discounted_price"].min())
print("Average Discount %:", df["discount_percentage"].mean())

Average Rating: 4.096584699453552
Highest Discounted Price: 77990.0
Lowest Discounted Price: 39.0
Average Discount %: 47.69146757679181


In [ ]:
print(df["main_category"].value_counts())

main_category
Electronics              526
Computers&Accessories    453
Home&Kitchen             448
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64





### ▶ **Practice Questions**


> **Note:** For this practice set, you'll be working with a **new dataset, `house_prices.csv`** (not `amazon.csv` from the earlier examples). Make sure you download `house_prices.csv` and load *that* file.

Q1. Loading the Dataset

Load house_prices.csv into a Pandas DataFrame named df. Display the first 5 rows and last 5 rows.

Q2. Inspecting the Dataset

Print the following:

Shape of the DataFrame
Column names
Data types of all columns


Q3. Understanding the Data

Use .info() to inspect the dataset. Identify three columns that are stored as object data type.


Q4. Data Cleaning — Price

The Amount(in rupees) column contains values such as:

42 Lac
98 Lac
1.40 Cr
25 Lac

Remove the extra spaces from this column and display the first 10 values.

Q5. Data Cleaning — Carpet Area

The Carpet Area column contains values such as:

500 sqft
473 sqft
779 sqft

Remove " sqft" from the values and convert the column into a numerical type.


Q6. Creating a Series

Create a Pandas Series using the following house prices:

[42, 98, 140, 25, 160]

Use the following labels:

House1, House2, House3, House4, House5

Display the price of House3 using its label and House5 using its position.

Q7. Selecting Columns

From the DataFrame, display only these columns:

Title
location
Price (in rupees)
Furnishing

Q8. Using .loc[]

Using .loc[], display rows 10 to 14 and only the following columns:

Title
location
Status
Furnishing

Q9. Using .iloc[]

Using .iloc[], display rows 5 to 9 and columns 1 to 5.

Q10. Filtering by Location

Display all houses where the location is "thane".


Q11. Filtering by Furnishing

Display all houses where Furnishing is "Furnished".


Q12. Multiple Conditions

Find houses that satisfy both conditions:

location is "thane"
Furnishing is "Unfurnished"

Display only:

Title
location
Furnishing
Price (in rupees)

Q13. Summary Operation

Using the Price (in rupees) column, find:

Average price
Maximum price
Minimum price

Q14. Summary Operation

Find the following for the Price (in rupees) column:

Median price
Average price

Also use .describe() to display the summary statistics.



Q15. Category Counting

Use value_counts() to find:

Number of properties for each Furnishing type.
Number of properties for each Transaction type.
Which Furnishing type occurs most frequently.